version: '3.7'
services:
  app:
    image: ${DOCKER_IMAGE_NAME:-devsecops-labs-app:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
